# Generated by Django 4.1.1 on 2022-09-22 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutoBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=250, verbose_name='Марка')),
                ('slug_brand', models.SlugField(verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='AutoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=250, verbose_name='Модель')),
                ('slug_model', models.SlugField(verbose_name='URL модели')),
                ('cat_car_brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='car.autobrand', verbose_name='Категория марки')),
            ],
        ),
        migrations.CreateModel(
            name='OwnerAuto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_owner', models.CharField(max_length=250, verbose_name='Имя Фамилия продавца')),
                ('brand_owner', models.CharField(max_length=250, verbose_name='Марка прдавца')),
                ('model_owner', models.CharField(max_length=250, verbose_name='Модель продавца')),
                ('photo', models.ImageField(upload_to='uploads/%Y/%m/%d/', verbose_name='Фото')),
                ('year_old', models.IntegerField(verbose_name='Год выпуска')),
                ('slug_owner', models.SlugField(verbose_name='URL владельца')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикация')),
                ('cat_car_brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='car.automodel', verbose_name='Ктегория модели')),
            ],
        ),
    ]
