# Generated by Django 4.1.1 on 2022-09-22 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autobrand',
            options={'ordering': ['brand'], 'verbose_name': 'Марка автомобиля', 'verbose_name_plural': 'Марка автомобиля'},
        ),
        migrations.AlterModelOptions(
            name='automodel',
            options={'ordering': ['model'], 'verbose_name': 'Модель автомобиля', 'verbose_name_plural': 'Модель автомобиля'},
        ),
        migrations.AlterModelOptions(
            name='ownerauto',
            options={'ordering': ['name_owner'], 'verbose_name': 'Продающаяся машина', 'verbose_name_plural': 'Продающаяся машина'},
        ),
        migrations.AddField(
            model_name='ownerauto',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('RUB', 'RUB'), ('BYN', 'BYN')], default='USD', max_length=50, verbose_name='Валюта'),
        ),
        migrations.AddField(
            model_name='ownerauto',
            name='prise',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Цена'),
        ),
    ]
