# Generated by Django 4.1.1 on 2022-09-23 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_alter_ownerauto_is_published_alter_ownerauto_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerauto',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
