# Generated by Django 4.1.1 on 2022-09-23 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_ownerauto_cat_car_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autobrand',
            name='sign_auto',
            field=models.ImageField(blank=True, upload_to='uploads/sign_auto/', verbose_name='фото значка'),
        ),
    ]
